version: '3'

services:

  api:
    image: node
    restart: always
    container_name: api
    command: npm run start:dev
    working_dir: /backend_api
    volumes:
      - ./:/backend_api
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - travel

  db:
    image: postgres:14
    restart: always
    container_name: db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
    networks:
      - travel

#  redis:
#    container_name: redis
#    hostname: redis
#    image: redis
#    restart: always
#    logging:
#      driver: none
#    networks:
#      - backend_api

#  nest-redis-commander:
#    container_name: nest-redis-commander
#    image: rediscommander/redis-commander:latest
#    restart: always
#    logging:
#      driver: none
#    environment:
#      - REDIS_HOSTS=local:redis:6379
#    ports:
#      - ${REDIS_COMMANDER_PORT}:${REDIS_COMMANDER_PORT}
#    networks:
#      - travel

networks:
  travel:
    name: docker_travel
    external: true